package view.SacPackage;

import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import map.Uzytkownik;
import map.Zamowienie;
import view.MainFrame;
import dao.UzytkownikDao;
import java.util.Date;
import dao.DAO;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
/**
 *
 * @author kubpi
 */
public class UzytForm extends javax.swing.JPanel {

    /**
     * Creates new form UzytForm
     */
    Uzytkownik uzytkownik;
   Uzytkownik uzytkownik1;
    Zamowienie zamowienie;
    String text_imie;
    String text_nazwisko;
    String text_nick;
    String text_haslo;
    

    public UzytForm(Uzytkownik user) {
        this.uzytkownik = user;
        initComponents();
        startProgram();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tfwpisznazwisko = new javax.swing.JTextField();
        tfwpiszimie = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfwpiszhaslo = new javax.swing.JTextField();
        lData = new javax.swing.JLabel();
        lImie = new javax.swing.JLabel();
        buttonZmienNazwisko = new javax.swing.JButton();
        lNazwisko = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tfwpisznick = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        buttonZmienHaslo = new javax.swing.JButton();
        buttonZmienNick = new javax.swing.JButton();
        buttonZmienImie = new javax.swing.JButton();
        lNick = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        zapiszButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        zobaczSzczegolyButton = new javax.swing.JButton();
        powrotButton = new javax.swing.JButton();

        setPreferredSize(Toolkit.getDefaultToolkit().getScreenSize());
        setRequestFocusEnabled(false);

        jPanel1.setBackground(new java.awt.Color(255, 69, 69));
        jPanel1.setPreferredSize(Toolkit.getDefaultToolkit().getScreenSize());
        jPanel1.setRequestFocusEnabled(false);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Sitka Heading", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Panel konta:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(455, 455, 455)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 885, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dane konta", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Sitka Heading", 1, 24))); // NOI18N
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setOpaque(false);

        jLabel3.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nazwisko:");

        tfwpisznazwisko.setText("jTextField1");
        tfwpisznazwisko.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfwpisznazwiskoActionPerformed(evt);
            }
        });

        tfwpiszimie.setText("jTextField2");
        tfwpiszimie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfwpiszimieActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Data zalozenia konta:");

        tfwpiszhaslo.setText("jTextField1");
        tfwpiszhaslo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfwpiszhasloActionPerformed(evt);
            }
        });

        lData.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        lData.setForeground(new java.awt.Color(255, 255, 255));
        lData.setText("TU BEDZIE WYŒWIETLANA DATA");

        lImie.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        lImie.setForeground(new java.awt.Color(255, 255, 255));
        lImie.setText("TU BÊDZIE WYŒWIETLANE IMIE");

        buttonZmienNazwisko.setText("Zmieñ");
        buttonZmienNazwisko.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonZmienNazwiskoActionPerformed(evt);
            }
        });

        lNazwisko.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        lNazwisko.setForeground(new java.awt.Color(255, 255, 255));
        lNazwisko.setText("TU BÊDZIE WYŒWIETLANE NAZWISKO");

        jLabel10.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Nick:");

        tfwpisznick.setText("jTextField1");
        tfwpisznick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfwpisznickActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Has³o:");

        buttonZmienHaslo.setText("Zmieñ");
        buttonZmienHaslo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonZmienHasloActionPerformed(evt);
            }
        });

        buttonZmienNick.setText("Zmieñ");
        buttonZmienNick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonZmienNickActionPerformed(evt);
            }
        });

        buttonZmienImie.setText("Zmieñ");
        buttonZmienImie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonZmienImieActionPerformed(evt);
            }
        });

        lNick.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        lNick.setForeground(new java.awt.Color(255, 255, 255));
        lNick.setText("TU BÊDZIE WYŒWIETLANY NICK");

        jLabel6.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Imie:");

        zapiszButton.setText("Zapisz");
        zapiszButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zapiszButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lNazwisko, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(180, 180, 180))
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lData, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(133, 133, 133))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lImie, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(buttonZmienImie, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tfwpiszimie, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(buttonZmienNazwisko, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tfwpisznazwisko, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfwpiszhaslo, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfwpisznick, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
                                .addComponent(buttonZmienNick, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(zapiszButton, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(88, 88, 88)
                                    .addComponent(buttonZmienHaslo, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lNick, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lImie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(tfwpiszimie, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonZmienImie, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNazwisko, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(tfwpisznazwisko, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonZmienNazwisko, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNick, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addComponent(tfwpisznick, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonZmienNick, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lData, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tfwpiszhaslo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonZmienHaslo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zapiszButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(105, 105, 105))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista z³o¿onych zamówieñ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Sitka Heading", 1, 24))); // NOI18N
        jPanel4.setOpaque(false);

        jLabel7.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Wybierz zamówienie:");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        zobaczSzczegolyButton.setText("Zobacz szczegó³y");
        zobaczSzczegolyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zobaczSzczegolyButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(zobaczSzczegolyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 888, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(zobaczSzczegolyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        powrotButton.setText("Powrot");
        powrotButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                powrotButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(powrotButton, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(powrotButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(903, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 496, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    private void tfwpisznazwiskoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfwpisznazwiskoActionPerformed
 
        
        text_nazwisko = tfwpisznazwisko.getText();
        

    }//GEN-LAST:event_tfwpisznazwiskoActionPerformed

    private void tfwpiszimieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfwpiszimieActionPerformed
       
        text_imie = tfwpiszimie.getText();
        
    }//GEN-LAST:event_tfwpiszimieActionPerformed

    private void tfwpiszhasloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfwpiszhasloActionPerformed

    }//GEN-LAST:event_tfwpiszhasloActionPerformed

    private void buttonZmienNazwiskoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonZmienNazwiskoActionPerformed
        tfwpisznazwiskoActionPerformed(evt);
        
        System.out.println("nazwisko" + text_nazwisko);

      
         
            lNazwisko.setText(text_nazwisko);
        
        
    }//GEN-LAST:event_buttonZmienNazwiskoActionPerformed

    private void tfwpisznickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfwpisznickActionPerformed
        text_nick = tfwpisznick.getText();
    }//GEN-LAST:event_tfwpisznickActionPerformed

    private void buttonZmienHasloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonZmienHasloActionPerformed
        uzytkownik.setPassword(text_haslo);
    }//GEN-LAST:event_buttonZmienHasloActionPerformed

    private void buttonZmienNickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonZmienNickActionPerformed
        tfwpisznickActionPerformed(evt);
        
        System.out.println("nick" + text_nick);
        
            
            lNick.setText(text_nick);
        
        
    }//GEN-LAST:event_buttonZmienNickActionPerformed

    private void buttonZmienImieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonZmienImieActionPerformed
        tfwpiszimieActionPerformed(evt);
       
        System.out.println("imie" + text_imie);
       
           
                    lImie.setText(text_imie);
        
        
    }//GEN-LAST:event_buttonZmienImieActionPerformed

    private void zobaczSzczegolyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zobaczSzczegolyButtonActionPerformed
//        Po naciÅ›niÄ™ciu przycisku zmiana widok
        MainFrame mf = (MainFrame) (JFrame) SwingUtilities.getWindowAncestor(this);
        mf.showOrderDetails();
    }//GEN-LAST:event_zobaczSzczegolyButtonActionPerformed

    private void zapiszButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zapiszButtonActionPerformed
       
         int id = uzytkownik.getIdUzytkownika();
         
         UzytkownikDao uzytkownikDao = new UzytkownikDao();
          uzytkownik1 = uzytkownikDao.getById(Long.valueOf(id));
          System.out.println("Przed wywolaniem funkcji zmieniajacych" + uzytkownik1.getImie());
          System.out.println("TO IMIE DO ZMIENIEA" + text_imie);
          
          
          buttonZmienImieActionPerformed(evt);
        buttonZmienNazwiskoActionPerformed(evt);
        buttonZmienNickActionPerformed(evt);
        buttonZmienHasloActionPerformed(evt);
        
          uzytkownik1.setImie(text_imie);
          uzytkownik1.setNazwisko(text_nazwisko);
          uzytkownik1.setPassword(text_haslo);
          uzytkownik1.setNickname(text_nick);
         
        
        System.out.println( "to jest uzytkownik1 - zmieniony" + uzytkownik1.getImie());
        uzytkownikDao.update(uzytkownik1);
        
    }//GEN-LAST:event_zapiszButtonActionPerformed

    private void powrotButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_powrotButtonActionPerformed
        MainFrame mf = (MainFrame) (JFrame) SwingUtilities.getWindowAncestor(this);
        mf.returnToShop();
    }//GEN-LAST:event_powrotButtonActionPerformed


     private void Jlist(){
//        ustawia zamówienia na liœcie

//         model = zamowienie.getIdZamowienia();
//        jList1.setModel((ListModel model);

//        po kliknieciu zrob cos - nwm czy potrzebne
//        jList1.addListSelectionListener(e -> {
//            if (!e.getValueIsAdjusting()) {
//                // Get the selected item from the JList
//                Zamowienie selectedItem = jList1.getSelectedValue();
//                // Do something with the selected item
//
//                System.out.println("Selected Item: " + selectedItem.getIdZamowienia() + " with ID: " + selectedItem.getAdres());
//            }
//        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonZmienHaslo;
    private javax.swing.JButton buttonZmienImie;
    private javax.swing.JButton buttonZmienNazwisko;
    private javax.swing.JButton buttonZmienNick;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lData;
    private javax.swing.JLabel lImie;
    private javax.swing.JLabel lNazwisko;
    private javax.swing.JLabel lNick;
    private javax.swing.JButton powrotButton;
    private javax.swing.JTextField tfwpiszhaslo;
    private javax.swing.JTextField tfwpiszimie;
    private javax.swing.JTextField tfwpisznazwisko;
    private javax.swing.JTextField tfwpisznick;
    private javax.swing.JButton zapiszButton;
    private javax.swing.JButton zobaczSzczegolyButton;
    // End of variables declaration//GEN-END:variables

    private void startProgram() {

        tfwpiszimie.setText("");
        tfwpiszhaslo.setText("");
        tfwpiszimie.setText("");
        tfwpisznazwisko.setText("");
        tfwpisznick.setText("");

        lData.setText(String.valueOf(uzytkownik.getDataZalozeniaKonta()));
        lImie.setText(uzytkownik.getImie());
        lNazwisko.setText(uzytkownik.getNazwisko());
        lNick.setText(uzytkownik.getNickname());

    }

}
